services:
  # course:
  #   build: 
  #     context: .
  #     dockerfile: ./apps/course/Dockerfile
  #   # target: development
  #   command: npm run start:dev course
  #   env_file:
  #     - ./apps/course/.env
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3000:3000"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  rabbitmq:
    image: rabbitmq
    ports: "5672:5672"